### ISSUE TITLE
help with scandoubler

### ISSUE THREAD

**Issue by nippur72** [mist-devel/mist-modules#4]
I have developed two different cores ([Laser500](https://github.com/nippur72/Laser500_MiST) and [LM80C](https://github.com/nippur72/LM80C_MiST)) the former runs in PAL and the latter in NTSC. 

I wrote them for 15 kHz and later added the scandoubler feature by simply plugging the module `mist_video.v`.

The problem is that VGA 31kHz signal isn't picked at all: the screen remains black with "no signal". Many other cores like VIC20 are fine and the 15kHz signal is also ok.

I wonder if is there anything specific I am missing that I should do.

Currently, I get the wires `scandoubler_disabler` and `no_csync` from `userio.v` and pass them to `mist_video.v`. I also have doubled the dot pixel frequency. Is that enough or is there something else?

**Comment by gyurco** [comment]
Maybe you should increase SD_HCNT_WIDTH. It's 9 by default to eat the least amount of BRAM, but it's not enough for higher pixel clocks.

**Comment by nippur72** [comment]
Increasing it from `9` to `11` did the job. Thanks.
