### ISSUE TITLE
i2s not working in amstrad PCW core

### ISSUE THREAD

**Issue by rampa069** [mist-devel/mist-modules#7]
The new i2s sounds really well.  I have changed it on some cores and it works.... but in one.

 The only thing can be different is clk_sys at 64MHz  make it sense?

(using the same signals with another module works ok)

```
`ifdef I2S_AUDIO

wire [31:0] clk_rate =  32'd32_000_000;
wire [15:0] dac_out ={audiomix,7'b0000000};

//i2s i2s (
//	.reset(reset),
//	.clk(i2s_clock),
//	.clk_rate(clk_rate),
//
//	.sclk(I2S_BCK),
//	.lrclk(I2S_LRCK),
//	.sdata(I2S_DATA),
//
//	.left_chan (dac_out),
//	.right_chan(dac_out)
//);

audio_top audio_top
(
  .clk_50MHz  (CLOCK_27),
  .dac_MCLK   (),
  .dac_LRCK   (I2S_LRCK),
  .dac_SCLK   (I2S_BCK),
  .dac_SDIN   (I2S_DATA),
  .L_data     ({~dac_out[15],dac_out[14:0]}),
  .R_data     ({~dac_out[15],dac_out[14:0]})
);

`endif
```

**Comment by gyurco** [comment]
If the clock is 64 MHz, then the clock rate also should be 32'd64_000_000.

**Comment by rampa069** [comment]
Yes. Was the first thing I tried. No sound at any rate... Silence....

**Comment by gyurco** [comment]
Strange. One note that it should be signed, so probably you should invert dac_out[15]. If still doesn't work, then the output could be compared from the two modules via SignalTap II.

**Comment by rampa069** [comment]
only was trying signed/unsigned....

 I have seen your core for CPC. it also have a 64MHZ clk_sys and i cant get sound from this also.....

(changed the i2s to the oldd one and it worked)


  Can you listen to your i2s in this core?

**Comment by gyurco** [comment]
Actually I couldn't test I2S yet, it's broken on the board I have.

**Comment by rampa069** [comment]
*update*

 Using a dedicated pll output at 24mhz to the i2s and setting the appropriate clk rate it sounds on all the cores I have tested.

**Comment by gyurco** [comment]
You mean dedicated pll output pin for MCLK?
Or just a dedicated PLL to create a 24 MHz clock for the I2S module? This can be a good approach, however the clock-domain crossing of the audio data from the core to I2S can have some unwanted side-effects.
(I also struggled with I2S to HDMI, jitter, clock skew and even crosstalk prevented it from using it properly).

**Comment by gyurco** [comment]
Seems there was a bug:
https://github.com/mist-devel/mist-modules/commit/9f47172249c5ac300402fdeebeb26cb176155a2c
Amstrad core works well with 64 MHz clk_sys:
https://github.com/gyurco/Amstrad_MiST/commit/7c4e51e910229b4fd7f1d88d2fb3fbecbdd90222
