### ISSUE TITLE
Add some kind of handshaking to data_io

### ISSUE THREAD

**Issue by Kyp069** [mist-devel/mist-modules#9]
I am using data_io to play TZX files in several cores and to load snapshots in a Jupiter Ace core.

In TZX case I have to download the file to a temporary buffer because cannot 'play' the tape on the fly. Data is sent much faster than is played. TZX module uses a strobe signal to request more data.

ACE files are compressed (some kind of byte-run compression) and also data is sent much faster than is processed.

It would be great if a strobe or pause signal could be added to data_io to handle downloads.

Thanks.

**Comment by gyurco** [comment]
Unfortunately the hardware SPI implementations don't care about the receiver, it's not possible to stop a DMA transfer with an external signal. In the core where I'm using the TZX (or TAP) player, the tape data is loaded into the SDRAM first, you should live with that.
If you want handshaking, you can use the random access method (sd_xx), where you can request data in one sector granularity.

**Comment by Kyp069** [comment]
Ok, thanks.
